# -*- coding: utf-8 -*-
"""lab_robot_calib_partial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJ5X1TAc6ihdzg0meeVnbRzVXc7ivkAv

# Multiple Linear Regression for Robot Calibration

In this lab, we will illustrate the use of multiple linear regression for calibrating robot control.  In addition to reviewing the concepts in the [multiple linear regression demo](https://github.com/pliugithub/MachineLearning/blob/master/unit03_mult_lin_reg/demo1_glucose.ipynb), you will see how to use multiple linear regression for time series data -- an important concept in dynamical systems such as robotics.

The robot data for the lab is taken generously from the TU Dortmund's [Multiple Link Robot Arms Project](https://rst.etit.tu-dortmund.de/forschung/robotik/leichtbau/details-tudor/).  As part of the project, they have created an excellent public dataset: [MERIt](https://rst.etit.tu-dortmund.de/forschung/robotik/leichtbau/details-tudor/#c11560) -- A Multi-Elastic-Link Robot Identification Dataset that can be used for understanding robot dynamics.  The data is from a three link robot:

<img src="https://rst.etit.tu-dortmund.de/storages/rst-etit/r/Media_Forschung/Robotik/Leichtbau/TUDORBild.png" height="200" width="200">


We will focus on predicting the current draw into one of the joints as a function of the robot motion.  Such models are essential in predicting the overall robot power consumption.  Several other models could also be used.

## Load and Visualize the Data
First, import the modules we will need.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline

"""The full MERIt dataset can be obtained from the [MERIt site](http://www.rst.e-technik.tu-dortmund.de/cms/en/research/robotics/TUDOR_engl/index.html#h3MERIt).  But, this dataset is large.  Included in this repository are two of the ten experiments.  Each experiments corresonds to 80 seconds of recorded motion.  We will use the following files:
* [exp1.csv](./exp1.csv) for training
* [exp2.csv](./exp2.csv) for test

If you are running this notebook on Google colab, you will need to run the following commands to load the files onto your local machine.  Otherwise, if you have clone the repository, the files should be in the directory as the notebook and you can skip this step.
"""

import os
from six.moves import urllib

for fn_dst in ['exp1.csv', 'exp2.csv']:
    fn_src = 'https://raw.githubusercontent.com/sdrangan/introml/master/unit03_mult_lin_reg/%s' % fn_dst

    if os.path.isfile(fn_dst):
        print('File %s is already downloaded' % fn_dst)
    else:
        print('Downloaded %s' % fn_dst)
        urllib.request.urlretrieve(fn_src, fn_dst)

"""Below, I have supplied the column headers in the `names` array.  Use the `pd.read_csv` command to load the training data in `exp1.csv`.  Use the `index_col` option to specify that column 0 (the one with time) is the *index* column.  You can review [simple linear regression demo](https://github.com/pliugithub/MachineLearning/blob/master/unit02_simp_lin_reg/demo_auto_mpg.ipynb) for examples of using the `pd.read_csv` command."""

names =[
    't',                                  # Time (secs)
    'q1', 'q2', 'q3',                     # Joint angle   (rads)
    'dq1', 'dq2', 'dq3',                  # Joint velocity (rads/sec)
    'I1', 'I2', 'I3',                     # Motor current (A)
    'eps21', 'eps22', 'eps31', 'eps32',   # Strain gauge measurements ($\mu$m /m )
    'ddq1', 'ddq2', 'ddq3'                # Joint accelerations (rad/sec^2)
]
# TODO 1
df = pd.read_csv('exp1.csv', index_col = 0, names = names)

"""Print the first six lines of the pandas dataframe and manually check that they match the first rows of the csv file."""

# TODO 2
print(df.head(6))

"""From the dataframe `df`, extract the time indices into a vector `t` and extract `I2`, the current into the second joint.  Place the current in a vector `y` and plot `y` vs. `t`.   Label the axes with the units."""

# TODO 3
y = df['I2']
t = df.index
plt.plot(t,y)
plt.xlabel('Time (s)')
plt.ylabel('Current (A)')
plt.title('Current vs. Time')
plt.show()

"""Use all the samples from the experiment 1 dataset to create the training data:
* `ytrain`:  A vector of all the samples from the `I2` column
* `Xtrain`:  A matrix of the data with the columns:  `['q2','dq2','eps21', 'eps22', 'eps31', 'eps32','ddq2']`
"""

# TODO 4
ytrain = df['I2']
Xtrain = df[['q2', 'dq2', 'eps21', 'eps22', 'eps31', 'eps32', 'ddq2']]

"""
## Fit a Linear Model
Use the `sklearn.linear_model` module to create a `LinearRegression` class `regr`."""

from sklearn import linear_model

# Create linear regression object
# TODO 5
regr = linear_model.LinearRegression()

"""Train the model on the training data."""

# TODO 6
regr.fit(Xtrain, ytrain)

"""Using the trained model, compute, `ytrain_pred`, the predicted current.  Plot `ytrain_pred` vs. time `t`.  On the same plot, plot the actual current `ytrain` vs. time `t`.  Create a legend for the plot."""

# TODO 7
ytrain_pred = regr.predict(Xtrain)
plt.plot(t, ytrain_pred, label = 'Predicted')
plt.plot(t, ytrain, label = 'Actual')
plt.xlabel('Time (s)')
plt.ylabel('Current (A)')
plt.title('Current vs. Time')
plt.legend()
plt.show()

"""Measure the normalized RSS given by $RSS / (n s^2_y)$."""

# TODO 8
RSS_train = np.mean((ytrain - ytrain_pred)**2) / np.var(ytrain)
print(RSS_train)

"""## Measure the Fit on an Indepdent Dataset

Up to now, we have only tested the model on the same data on which it was trained.  In general, we need to test model on independent data not used in the training.  For this purpose, load the data in `exp2.csv`.  Compute the regression predicted values on this data and plot the predicted and actual values over time.
"""

# TODO 9
df_test = pd.read_csv('exp2.csv', index_col= 0, names = names)
t_test = df_test.index
Xtest = df_test[['q2','dq2','eps21','eps22','eps31','eps32','ddq2']]
ytest = df_test['I2']

ytest_pred = regr.predict(Xtest)

plt.plot(t_test, ytest_pred, label = 'Predicted Value')
plt.plot(t_test, ytest, label = 'Actual Value')
plt.xlabel('Time(s)')
plt.ylabel('Current(A)')
plt.legend()
plt.show()

"""Measure the normalized RSS on the test data."""

# TODO 10
RSS_test = np.mean((ytest - ytest_pred) **2)/np.var(ytest)
print(RSS_test)

